FROM php:8.0.2-fpm

# Arguments I defined in docker-compose.yml file
ARG user
ARG uid

# Install necessary system dependencies for the application
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libxml2-dev \
    libpng-dev \
    libonig-dev \
    zip \
    unzip \

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Composer installation, set to latest version
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

#  Composer for system user alongside php artisan commands
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

# Working Directory
WORKDIR /var/www

USER $user
